#!/bin/bash
# Assemble static site from .next build output for Cloudflare Pages
set -e
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

echo "Assembling static site from .next build output..."

rm -rf out
mkdir -p out

# 1. Copy static assets
mkdir -p out/_next
cp -r .next/static out/_next/

# 2. Copy public assets (images, favicon, etc.)
if [ -d "public" ]; then
  cp -r public/* out/
fi

# 3. Copy pre-rendered HTML pages
find .next/server/app -name "*.html" ! -name "_not-found*" | while read -r html_file; do
  # Get relative path from .next/server/app/
  rel="${html_file#.next/server/app/}"
  route="${rel%.html}"

  if [[ "$route" == "index" ]]; then
    cp "$html_file" "$ROOT/out/index.html"
  else
    mkdir -p "$ROOT/out/${route}"
    cp "$html_file" "$ROOT/out/${route}/index.html"
  fi
done

# 4. Copy route handler outputs (robots.txt only; sitemaps generated by script)
for route_file in .next/server/app/robots.txt.body; do
  if [ -f "$route_file" ]; then
    output_name="${route_file#.next/server/app/}"
    output_name="${output_name%.body}"
    cp "$route_file" "$ROOT/out/${output_name}"
    echo "Copied ${output_name}"
  fi
done

# 5. Verify sitemaps were copied from public/
for sm in sitemap.xml sitemap-pages.xml sitemap-characters.xml sitemap-weapons.xml sitemap-guides.xml sitemap-other.xml; do
  if [ -f "$ROOT/out/$sm" ]; then
    echo "Found ${sm}"
  else
    echo "WARNING: ${sm} not found in out/"
  fi
done

echo "Static site assembled."
echo "HTML pages: $(find out -name '*.html' | wc -l)"
echo "Total files: $(find out -type f | wc -l)"
